### PR TITLE
Fix scale back to 0 with 300 requests scenario

### LINKED ISSUE #73: Scale to 0 not working with replicas 3
```
2024/02/07 07:11:45 SetDesiredScale(0)                                                                          
2024/02/07 07:11:45 Is leader, autoscaling                                                                      
2024/02/07 07:11:45 Average for deployment: lingo: 0 (ceil: 0), current wait count: 0       
2024/02/07 07:11:45 SetDesiredScale(0)                                                                          
2024/02/07 07:11:45 Is leader, autoscaling                                                                      
2024/02/07 07:11:45 Average for deployment: stapi-minilm-l6-v2: 0 (ceil: 0), current wait count: 0              
2024/02/07 07:11:45 SetDesiredScale(0)                                                                          
2024/02/07 07:11:45 Comparing scales, current: 2, desired: 0                                                    
2024/02/07 07:11:48 Calculating scales for all                                                                  
2024/02/07 07:11:48 Leader active requests for: lingo: 0                                          
2024/02/07 07:11:48 Leader active requests for: stapi-minilm-l6-v2: 0                                           
2024/02/07 07:11:48 Leader active requests for: kubernetes: 0                               
2024/02/07 07:11:48 Aggregating active requests for endpoint: 10.244.0.6:8083: kubernetes: 0
2024/02/07 07:11:48 Aggregating active requests for endpoint: 10.244.0.6:8083: lingo: 0   
2024/02/07 07:11:48 Aggregating active requests for endpoint: 10.244.0.6:8083: stapi-minilm-l6-v2: 0
2024/02/07 07:11:48 Aggregating active requests for endpoint: 10.244.0.7:8083: kubernetes: 0
2024/02/07 07:11:48 Aggregating active requests for endpoint: 10.244.0.7:8083: lingo: 0
2024/02/07 07:11:48 Aggregating active requests for endpoint: 10.244.0.7:8083: stapi-minilm-l6-v2: 0
2024/02/07 07:11:48 Is leader, autoscaling                                                                      
2024/02/07 07:11:48 Average for deployment: lingo: 0 (ceil: 0), current wait count: 0               
2024/02/07 07:11:48 SetDesiredScale(0)                                                                          
2024/02/07 07:11:48 Is leader, autoscaling                                                                      
2024/02/07 07:11:48 Average for deployment: stapi-minilm-l
2024/02/07 07:11:48 SetDesiredScale(0)
2024/02/07 07:11:51 Calculating scales for all
2024/02/07 07:11:51 Leader active requests for: kubernetes: 0
2024/02/07 07:11:51 Leader active requests for: lingo: 0
2024/02/07 07:11:51 Leader active requests for: stapi-minilm-l6-v2: 0
2024/02/07 07:11:51 Aggregating active requests for endpoint: 10.244.0.7:8083: stapi-minilm-l6-v2: 0
2024/02/07 07:11:51 Aggregating active requests for endpoint: 10.244.0.7:8083: kubernetes: 0
2024/02/07 07:11:51 Aggregating active requests for endpoint: 10.244.0.7:8083: lingo: 0
2024/02/07 07:11:51 Aggregating active requests for endpoint: 10.244.0.6:8083: lingo: 0
2024/02/07 07:11:51 Aggregating active requests for endpoint: 10.244.0.6:8083: stapi-minilm-l6-v2: 0
2024/02/07 07:11:51 Aggregating active requests for endpoint: 10.244.0.6:8083: kubernetes: 0
2024/02/07 07:11:51 Is leader, autoscaling
2024/02/07 07:11:51 Average for deployment: kubernetes: 0 (ceil: 0), current wait count: 0
2024/02/07 07:11:51 SetDesiredScale(0)
2024/02/07 07:11:51 Is leader, autoscaling
2024/02/07 07:11:51 Average for deployment: lingo: 0 (ceil: 0), current wait count: 0
2024/02/07 07:11:51 SetDesiredScale(0)
2024/02/07 07:11:51 Is leader, autoscaling
2024/02/07 07:11:51 Average for deployment: stapi-minilm-l6-v2: 0 (ceil: 0), current wait count: 0
2024/02/07 07:11:51 SetDesiredScale(0)
2024/02/07 07:11:51 Comparing scales, current: 2, desired: 0
```

It looks like it should be scaling back to 0 but it just never does, it stays in this state indefinitely.

This is reproducible on main if you run the following:
```
export REPLICAS=3
export REQUESTS=300
export EXPECTED_REPLICAS=2
make test-e2e
```

### PR DESCRIPTION
**Pull request by samos123**
Fixes #73 and includes pr #70 and others from Alex

* Remove compareScales function
* Refactor SetDesiredScale that is simpler to understand by storing lastSuccessfulScale time
* Improve test coverage for scaler.go

Co-author: @alpe

### CODE REVIEW

File: pkg/deployments/scaler.go [hunk 1]
```diff
@@ -84,19 +84,22 @@ func (s *scaler) compareScales(current, desired int32) {
...
-		}
-		s.scaleDownStarted = false
+		s.stopScaleDown()
 	} else {
 		// Schedule a scale down.
-
 		if s.scaleDownTimer == nil {
 			s.scaleDownTimer = time.AfterFunc(s.scaleDownDelay, func() {
-				if err := s.scaleFunc(s.desiredScale, false); err != nil {
+				s.mtx.Lock()
```
Comment (samos123) [inline pkg/deployments/scaler.go:95]: The beginning of the function already has a .Lock and defer .Unlock(). Why do we need to do it again?

Comment (alpe) [reply pkg/deployments/scaler.go:95]: The code is called later in a separate Go routine. A new lock is required therefore

File: pkg/deployments/scaler.go [hunk 2]
```diff
@@ -46,69 +70,53 @@ func (s *scaler) UpdateState(replicas, min, max int32) {
...
-			s.scaleDownTimer.Stop()
-		}
-		s.scaleDownStarted = false
+		log.Println("Desired scale equals current scale, doing nothing")
 	} else {
-		// Schedule a scale down.
-
-		if s.scaleDownTimer == nil {
-			s.scaleDownTimer = time.AfterFunc(s.scaleDownDelay, func() {
+		if time.Since(s.lastScaleDown) >= s.scaleDownDelay {
```
Comment (alpe) [inline pkg/deployments/scaler.go:92]: 🤔 the `lastScaleDown` value is set in the constructor. This ensures the scale down delay is taken into account on a node startup and right after the last successful scale down. 
There is no delay if a running node becomes leader or if the last scale down is some time ago.  A scale down call would execute immediately as the condition is always true.
With the old logic, the first call to scale down triggered a timer. I order to achieve the same, we can have an unset `lastScaleDown` time and set it on first call to scale down. You can check with `s.lastScaleDown.IsZero()` for unset.
It should be cleared (unset) on 
* desiredScale >= currentScale
* successful scale down
* loosing leader role
* Probably with `AtLeastOne()`

File: pkg/deployments/manager.go [hunk 3]
```diff
@@ -103,6 +113,13 @@ func (r *Manager) addDeployment(ctx context.Context, d appsv1.Deployment) error
 	return nil
 }
 
+func (r *Manager) HasModel(deploymentName string) bool {
+	r.deploymentsMtx.RLock()
+	defer r.deploymentsMtx.RUnlock()
+	_, exists := r.deployments[deploymentName]
+	return exists
+}
+
```
Comment (alpe) [inline pkg/deployments/manager.go:122]: Please remove the deployment in `removeDeployment()`

**Review by alpe — COMMENTED** [review]
Good refactoring and simpler to read. I added some comments as I think the logic has changed for scale down. This is not necessarily bad but should be revisited from a product view.

File: pkg/autoscaler/autoscaler.go [hunk 4]
```diff
@@ -93,6 +93,11 @@ func (a *Autoscaler) Start() {
 		}
 
 		for deploymentName, waitCount := range stats.ActiveRequests {
+			// TODO remove this check and ensure only stats for deployments with models are returned
+			if !a.Deployments.HasModel(deploymentName) {
```
Comment (nstogner) [inline pkg/autoscaler/autoscaler.go:97]: What scenario leads lingo to fall into this state?

File: pkg/deployments/manager.go [hunk 5]
```diff
@@ -39,6 +40,10 @@ type Manager struct {
 
 	ScaleDownPeriod time.Duration
 
+	deploymentsMtx sync.RWMutex
+	// deployments is a set of deployment names that are managed by the Manager
+	deployments map[string]struct{}
```
Comment (nstogner) [inline pkg/deployments/manager.go:45]: This appears to be an grow-only map as implemented. Why do we need to track this here?

File: pkg/deployments/scaler.go [hunk 6]
```diff
@@ -14,13 +14,37 @@ type scaler struct {
...
+	scaleDownDelay time.Duration
+}
+
+func newScaler(scaleDownDelay time.Duration, scaleFunc func(int32, bool) error) *scaler {
+	s := &scaler{
+		// -1 represents unknown
+		currentScale:   -1,
+		desiredScale:   -1,
+		scaleDownDelay: scaleDownDelay,
+		lastScaleDown:  time.Now(),
```
Comment (nstogner) [inline pkg/deployments/scaler.go:32]: Use `time.Time{}` (empty time) for this.

File: pkg/deployments/scaler.go [hunk 7]
```diff
@@ -14,13 +14,37 @@ type scaler struct {
...
 	scaleFuncMtx sync.Mutex
 	scaleFunc    func(n int32, atLeastOne bool) error
 
-	scaleDownDelay   time.Duration
-	scaleDownStarted bool
-	scaleDownTimer   *time.Timer
+	scaleDownDelay time.Duration
+}
+
+func newScaler(scaleDownDelay time.Duration, scaleFunc func(int32, bool) error) *scaler {
```
Comment (nstogner) [inline pkg/deployments/scaler.go:26]: In future, it would be nice to keep the functions in place to avoid the noisy diff (its hard to know exactly what was changed here)... We can do re-ordering in another PR that does not change logic.

File: pkg/deployments/scaler.go [hunk 8]
```diff
@@ -46,69 +70,53 @@ func (s *scaler) UpdateState(replicas, min, max int32) {
...
-		n = min
-	} else if n > max {
-		n = max
-	}
-	return n
-}
-
-func (s *scaler) compareScales(current, desired int32) {
+	log.Printf("SetDesiredScale(%v), current: %v, min: %v, max: %v", n, s.currentScale, s.minScale, s.maxScale)
+	nMinMax := s.applyMinMax(n)
```
Comment (nstogner) [inline pkg/deployments/scaler.go:74]: No need for local var, clearer to do `s.desiredScale = s.applyMinMax(n)`

File: pkg/deployments/scaler.go (hunk 2 above)
Comment (nstogner) [reply pkg/deployments/scaler.go:92]: Here is my code I was working on in parallel:

```go
	if s.currentScale < s.desiredScale {
		// Scale up immediately.
		go s.scaleFunc(s.desiredScale, false)
		s.desiredScaleDownStart = time.Time{}
	} else if s.currentScale == s.desiredScale {
		s.desiredScaleDownStart = time.Time{}
	} else {
		if s.desiredScaleDownStart.IsZero() {
			s.desiredScaleDownStart = time.Now()
		} else if time.Since(s.desiredScaleDownStart) >= s.scaleDownDelay {
			go s.scaleFunc(s.desiredScale, false)
		}
	}
```

File: pkg/deployments/scaler_test.go [hunk 9]
```diff
@@ -74,8 +95,10 @@ func TestSetDesiredScale(t *testing.T) {
 			// Action
 			s.SetDesiredScale(tc.desiredScale)
 
-			// Wait for the scale function to be called
-			mockScaleWG.Wait()
+			if tc.expectedScaleFunc {
+				// Wait for the scale function to be called
+				mockScaleWG.Wait()
```
Comment (nstogner) [inline pkg/deployments/scaler_test.go:100]: Prefer to do a conditional `wg.Add(1)` instead of the conditional `.Wait()`.

**Review by nstogner — CHANGES_REQUESTED** [review]

File: pkg/deployments/scaler.go [hunk 10]
```diff
@@ -46,69 +70,53 @@ func (s *scaler) UpdateState(replicas, min, max int32) {
...
-	log.Printf("Comparing scales, current: %v, desired: %v", s.currentScale, s.desiredScale)
+	s.desiredScale = nMinMax
 
 	if s.desiredScale > s.currentScale {
 		// Scale up immediately.
-		go s.scaleFunc(s.desiredScale, false)
-		s.scaleDownStarted = false
+		log.Printf("Scaling up immediately")
+		go func() {
+			if err := s.scaleFunc(s.desiredScale, false); err != nil {
```
Comment (nstogner) [inline pkg/deployments/scaler.go:83]: Idiomatic way of doing this is to only check error condition, and return early on error instead of `if ... else`

File: pkg/deployments/manager.go (hunk 3 above)
Comment (samos123) [reply pkg/deployments/manager.go:122]: done, great catch!

File: pkg/deployments/scaler.go (hunk 2 above)
Comment (samos123) [reply pkg/deployments/scaler.go]: Thanks for taking the time to do a deeper analysis on how it differs. I agree that setting it to zero value is cleaner and have fixed it.

@nstogner regarding your implementation, it's important that we always check and log the error of s.scaleFunc because otherwise it will be hard to debug if there is a scaling issue. Was there any reason we weren't originally doing error checks? and any reason why your implementation does not? Just making sure I'm not doing something useless with the error checking.

File: pkg/deployments/scaler.go (hunk 8 above)
Comment (samos123) [reply pkg/deployments/scaler.go:73]: but s.applyMinMax will call `Lock()` so that's why I did this. Is that not needed even when it also calls `Lock()`?

Comment (samos123) [reply pkg/deployments/scaler.go:73]: I'm pretty sure this would result in a deadlock unless I use the local var, see code example here which simulates what would happen if I were to call s.desiredCale = s.applyMinMax(n) within the Lock()
```

func main() {
	mtx := sync.Mutex{}
	mtx.Lock()
	fmt.Println("Locked")
	mtx.Lock()
	fmt.Println("Double locked")
}
```

File: pkg/deployments/scaler.go (hunk 10 above)
Comment (samos123) [reply pkg/deployments/scaler.go:82]: fixed, agree that does seem a bit cleaner

File: pkg/deployments/scaler.go (hunk 7 above)
Comment (samos123) [reply pkg/deployments/scaler.go:26]: ok will do. I will do 2 PRs and then base 2nd PR on the 1st refactor PR that doesn't change logic

File: pkg/deployments/scaler.go (hunk 6 above)
Comment (samos123) [reply pkg/deployments/scaler.go]: I think just not initializing does the same thing? Can you verify the latest code? it seems to all work as expected right now.

File: pkg/deployments/manager.go (hunk 5 above)
Comment (samos123) [reply pkg/deployments/manager.go:45]: so we can do HasModel because stats aggregates stats of all deployments and autoscaler is active on all deployments. I had to do this to get it to work.

File: pkg/autoscaler/autoscaler.go (hunk 4 above)
Comment (samos123) [reply pkg/autoscaler/autoscaler.go:97]: Lingo right now has autoscaler active on all deployments because ActiceRequests returns the active requests for all deployments. This if statement can be removed once we fix https://github.com/substratusai/lingo/issues/59 and use Pod endpoints and only add endpoints of Deployments that have a lingo model annotation.

Comment (samos123) [reply pkg/autoscaler/autoscaler.go:97]: To answer your question, this happens in all scenarios.

File: pkg/autoscaler/autoscaler.go [hunk 11]
```diff
@@ -93,6 +93,11 @@ func (a *Autoscaler) Start() {
...
+				log.Printf("Deployment: %v has no model annotations, skipping", deploymentName)
```
[the remark this answers is not in the document]
Comment (samos123) [reply pkg/autoscaler/autoscaler.go:98]: I think we can remove this log once we remove this if statement. The logs are confusing without a log saying that the deployment is ignored. The reason being that earlier in the log it shows aggregating stats of e.g. kubernetes which might make people think it's active on the kubernetes service.

File: pkg/deployments/scaler.go (hunk 8 above)
Comment (nstogner) [reply pkg/deployments/scaler.go:73]: You can call it before the `Lock()`

Comment (samos123) [reply pkg/deployments/scaler.go:73]: but I shouldn't modify `s.desiredScale` before calling `Lock()`?

Comment (samos123) [reply pkg/deployments/scaler.go]: after quick chat, I fixed this by removing the lock in applyMinMax and moving the call to applyMinMax into the lock itself.

File: pkg/deployments/scaler_test.go [hunk 12]
```diff
@@ -89,3 +76,111 @@ func TestSetDesiredScale(t *testing.T) {
...
+	mockScaleMtx.Unlock()
+	s.UpdateState(7, 1, 10)
+	// Wait for scale down delay to pass
+	time.Sleep(2*time.Second + 10*time.Millisecond)
+
+	// Trigger a scale down
+	s.SetDesiredScale(3)
+	time.Sleep(1 * time.Second)
+	mockScaleMtx.Lock() // Ensure consistency of the checked state
+	if scaleFuncCalled != false {
```
Comment (nstogner) [inline pkg/deployments/scaler_test.go:173]: You could also use `require.True(t, scaleFuncCalled)` - https://pkg.go.dev/github.com/stretchr/testify/require#True

**Review by nstogner — APPROVED** [review]
LGTM - added one small suggestion in tests
