### PR TITLE
add python openai multithread system test and fix hang in completeFunc

### LINKED ISSUE #22: HTTP responses aren't closed and left open
This causes the HTTP request to hang and never fully close

Steps to reproduce:
```
skaffold run
helm upgrade --install stapi-minilm-l6-v2 substratusai/stapi -f - << EOF
model: all-MiniLM-L6-v2
replicaCount: 0
deploymentAnnotations:
  lingo.substratus.ai/models: text-embedding-ada-002
EOF
curl -v http://localhost:8080/v1/embeddings \
  -H "Content-Type: application/json" \
  -d '{
    "input": "Your text string goes here",
    "model": "text-embedding-ada-002"
  }'
```

relevant logs:
```
2023/11/12 04:28:06 request: /v1/embeddings
2023/11/12 04:28:06 model: text-embedding-ada-002
2023/11/12 04:28:06 AtLeastOne()
2023/11/12 04:28:06 Entering queue
2023/11/12 04:28:06 Admitted into queue
2023/11/12 04:28:06 Waiting for IPs
2023/11/12 04:28:06 Scaling model "stapi-minilm-l6-v2": 1
Dequeued:  2cb28540-19a1-4b1e-aa9f-a6fdf14eac6c
2023/11/12 04:28:06 request: /v1/embeddings
2023/11/12 04:28:06 model: text-embedding-ada-002
2023/11/12 04:28:06 AtLeastOne()
2023/11/12 04:28:06 Entering queue
Dequeued:  2476f903-12fd-4d76-9cda-c128628ca43a
2023/11/12 04:28:06 Admitted into queue
2023/11/12 04:28:06 Waiting for IPs
2023/11/12 04:28:06 request: /v1/embeddings
2023/11/12 04:28:06 model: text-embedding-ada-002
2023/11/12 04:28:06 AtLeastOne()
2023/11/12 04:28:06 Entering queue
```

This seems to be introduced by #19

### PR DESCRIPTION
**Pull request by samos123**
Fixes #22

### CODE REVIEW

File: handler.go [hunk 1]
```diff
@@ -103,6 +105,30 @@ func newReverseProxy(host string) *httputil.ReverseProxy {
 			r.Out.Host = r.In.Host
 			AdditionalProxyRewrite(r)
 		},
+		Transport: &retryTransport{
```
Comment (nstogner) [inline handler.go:108]: I would prefer to avoid this. Retries at multiple levels (client retry, proxy retry) make things difficult to debug. It will also likely mask problems that should otherwise be solved.

File: integration_test.go [hunk 2]
```diff
@@ -90,22 +94,25 @@ func requireDeploymentReplicas(t *testing.T, deploy *appsv1.Deployment, n int32)
 
 func sendRequests(t *testing.T, wg *sync.WaitGroup, modelName string, n int) {
 	for i := 0; i < n; i++ {
-		sendRequest(t, wg, modelName)
+		sendRequestWG(t, wg, modelName)
 	}
 }
 
-func sendRequest(t *testing.T, wg *sync.WaitGroup, modelName string) {
+func sendRequest(t *testing.T, modelName string) {
```
Comment (nstogner) [inline integration_test.go:101]: Can we revert these changes?

**Review by nstogner — CHANGES_REQUESTED** [review]

File: handler.go (hunk 1 above)
Comment (samos123) [reply handler.go]: done

File: integration_test.go (hunk 2 above)
Comment (samos123) [reply integration_test.go]: done

**Review by nstogner — APPROVED** [review]
